CREATE DATABASE test;
USE test;
CREATE TABLE STUDENT(ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(30),
ADDRESS VARCHAR(30),
PRIMARY KEY(ID));
SELECT  * FROM STUDENT;
INSERT INTO STUDENT(NAME,ADDRESS)
VALUES('Rashida','sector-6'),('NUSRAT','sector-7'),('Sristy','sector-5');
SELECT  * FROM STUDENT;

CREATE TABLE STUDENT_TAKEN(ID INT NOT NULL AUTO_INCREMENT,
subj_code VARCHAR(30),
std_id INT,FOREIGN KEY(std_id) REFERENCES STUDENT(ID),
PRIMARY KEY(ID));
INSERT INTO STUDENT_TAKEN(subj_code,std_id)
VALUES('CSEC221',1),('CSEC222',2);
SELECT  * FROM STUDENT_TAKEN;

SELECT * FROM STUDENT,STUDENT_TAKEN
WHERE STUDENT.ID=STUDENT_TAKEN.std_id;

SELECT * FROM STUDENT INNER JOIN
STUDENT_TAKEN ON 
STUDENT.ID=STUDENT_TAKEN.std_id;

SELECT * FROM STUDENT RIGHT  JOIN
STUDENT_TAKEN ON 
STUDENT.ID=STUDENT_TAKEN.std_id;

SELECT * FROM STUDENT LEFT   JOIN
STUDENT_TAKEN ON 
STUDENT.ID=STUDENT_TAKEN.std_id;